#!/bin/sh

HOMEDIR="~/cve"




wget -V > /dev/null 2>&1;
if [ $? -ne 0 ];
then
  echo "This script requires scp to be available on the system and reachable in a directory mentioned in the PATH variable."
  exit 1;
fi


cd ${HOMEDIR}

WGETCMD="wget --no-check-certificate";


echo "Check download.log"

for YEAR in $(seq -w 02 `date +%y`);
do
    if [ ! -f ${CVECACHE}/nvdcve-2.0-20${YEAR}.xml ];
    then
        echo "Downloading nvdcve-2.0-20${YEAR}.xml... " > ~/cve/download.log
        ${WGETCMD} -q -O ${CVECACHE}/nvdcve-2.0-20${YEAR}.xml.gz https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-20${YEAR}.xml.gz;
    fi
done


if [ ! -f nvdcve-2.0-modified.xml ];
then
  CKSUM="1"
else
  CKSUM=$(cksum nvdcve-2.0-modified.xml 2>/dev/null);
fi
printf "Downloading nvdcve-2.0-modified.xml... ";
${WGETCMD} -q https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-modified.xml.gz nvdcve-2.0-modified.xml.gz;








